// import '@common/types/common'
// import '@common/types/user_api'
// import '@common/types/sync'
// import '@common/types/music'
// import '@common/types/list'
// import '@common/types/download_list'
import '@common/types/shims_vue'
// import '@common/types/utils'
import '@common/types/theme'
import '@common/types/desktop_lyric'
import '@common/types/player'
import '@common/types/ipc_renderer'
// 迷你播放窗入口共用本 tsconfig，需要应用设置类型（如 LX.AppSetting）
import '@common/types/app_setting'
