import { ref } from '@renderer/utils/vueTools'

export const currentStting = ref({
  player: {
    togglePlayMethod: 'listLoop',
    highQuality: false,
    isShowTaskProgess: true,
    volume: 1,
    isMute: false,
    mediaDeviceId: 'default',
    isMediaDeviceRemovedStopPlay: false,
    isShowLyricTranslation: false,
    isShowLyricRoma: false,
    isS2t: false, // 是否将歌词从简体转换为繁体
    isPlayLxlrc: true,
    isSavePlayTime: false,
    audioVisualization: false,
    waitPlayEndStop: true,
    waitPlayEndStopTime: '',
    autoSkipOnError: true,
  },
  playDetail: {
    isZoomActiveLrc: true,
    style: {
      fontSize: 100,
      align: 'center',
    },
  },
  desktopLyric: {
    enable: false,
    isLock: false,
    width: 600,
    height: 700,
    x: -1,
    y: -1,
    theme: '',
    isLockScreen: true,
    isDelayScroll: true,
    isHoverHide: false,
    style: {
      font: '',
      fontSize: 125,
      opacity: 80,
      isZoomActiveLrc: true,
    },
  },
  list: {
    isShowAlbumName: true,
    isShowSource: true,
    isSaveScrollLocation: true,
  },
  search: {
    searchSource: 'kw',
    tempSearchSource: 'kw',
    isShowHotSearch: false,
    isShowHistorySearch: false,
    isFocusSearchBox: false,
  },
  download: {
    enable: false,
    savePath: '',
    fileName: '歌名 - 歌手',
    isDownloadLrc: false,
    lrcFormat: 'utf8',
    isEmbedPic: true,
    isEmbedLyric: true,
  },
  network: {
    proxy: {
      enable: false,
      host: '',
      port: '',
      username: '',
      password: '',
    },
  },
  odc: {
    isAutoClearSearchInput: false,
    isAutoClearSearchList: false,
  },
  tray: {
    isShow: false,
    isToTray: false,
    themeId: 0,
  },
  sync: {
    enable: false,
    port: '23332',
  },
  windowSizeId: 1,
  startInFullscreen: false,
  langId: 'cns',
  theme: {
    id: 0,
    lightId: 0,
    darkId: 13,
  },
  sourceId: 0,
  font: '',
  isShowAnimation: true,
  randomAnimate: true,
  isAgreePact: false,
  controlBtnPosition: 'left',
  apiSource: 'temp',
})
